version: '3.8'

services:

  gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  annotation:
    build: ./annotation_service
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  pattern:
    build: ./pattern_service
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload

  tracking:
    build: ./tracking_service
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8003 --reload

  scene:
    build: ./video-scene-splitter
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8004 --reload

  face:
    build: ./face-detector
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8005 --reload

  export:
    build: ./export_service
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8006 --reload

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - gateway
    command: npm run dev

  mongo:
    image: mongo:5
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
